"""Static employee support FAQ dataset for EMS chatbot."""

FAQ_ITEMS = [
    {
        "id": "reset-password",
        "question": "How can I reset my password?",
        "keywords": ["reset", "password", "forgot", "login"],
        "answer": (
            "Contact HR/Admin to reset your password from the admin panel. "
            "After reset, log in with the temporary password and update it immediately."
        ),
    },
    {
        "id": "attendance-missing",
        "question": "My attendance is missing. What should I do?",
        "keywords": ["attendance", "missing", "absent", "mark", "present"],
        "answer": (
            "Open your attendance report and confirm the date first. "
            "If still missing, share the exact date and shift details with HR/Admin for correction."
        ),
    },
    {
        "id": "leave-apply",
        "question": "How do I apply for leave?",
        "keywords": ["leave", "apply", "vacation", "sick", "holiday"],
        "answer": (
            "Use the employee dashboard Leave section, choose the date, and submit. "
            "You can track approved leaves in your attendance summary."
        ),
    },
    {
        "id": "timesheet-update",
        "question": "How can I edit or update my timesheet?",
        "keywords": ["timesheet", "update", "edit", "work details", "hours"],
        "answer": (
            "Submit corrected work details for the right date/time slot. "
            "If a locked or wrong entry exists, ask Admin to remove the old record first."
        ),
    },
    {
        "id": "payroll-delay",
        "question": "Why is my salary not generated yet?",
        "keywords": ["salary", "payroll", "delay", "not generated", "payslip"],
        "answer": (
            "Payroll is generated by Admin based on attendance and configured salary data. "
            "If delayed, verify attendance and contact payroll support for the processing timeline."
        ),
    },
    {
        "id": "payroll-history",
        "question": "Where can I see my payroll history?",
        "keywords": ["payroll", "history", "salary", "previous", "month"],
        "answer": (
            "Go to your dashboard payroll/history view. "
            "You can check month-wise generated payroll records there."
        ),
    },
    {
        "id": "phone-update",
        "question": "How do I update my phone number?",
        "keywords": ["phone", "mobile", "number", "update", "change"],
        "answer": (
            "Personal profile updates are managed by HR/Admin. "
            "Raise a support request with your employee ID and new phone number."
        ),
    },
    {
        "id": "working-hours",
        "question": "How are total workdays calculated?",
        "keywords": ["workdays", "working", "hours", "calculated", "attendance report"],
        "answer": (
            "Workdays are computed from recorded attendance and approved work details. "
            "Leaves are tracked separately in your attendance report."
        ),
    },
    {
        "id": "account-locked",
        "question": "My account is locked. How can I unlock it?",
        "keywords": ["account", "locked", "unlock", "login failed"],
        "answer": (
            "If your account is locked after repeated failed logins, "
            "contact HR/Admin to unlock and reset access securely."
        ),
    },
    {
        "id": "contact-support",
        "question": "How do I contact employee support?",
        "keywords": ["support", "help", "contact", "issue", "ticket"],
        "answer": (
            "Share your issue with employee ID, date/time, and screenshot if available. "
            "Route login/attendance/payroll issues to HR/Admin support for faster resolution."
        ),
    },
]
